# Generated by Django 3.0.6 on 2020-07-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeMst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.CharField(db_index=True, help_text='数字で３桁入力してください.', max_length=3, verbose_name='大分類コード')),
                ('cdNm', models.CharField(help_text='20文字まで入力してください.', max_length=20, verbose_name='大分類名')),
                ('subCd', models.CharField(help_text='数字で３桁まで入力してください.', max_length=3, verbose_name='小分類コード')),
                ('subNm', models.CharField(help_text='20文字まで入力してください.', max_length=20, verbose_name='小分類名')),
                ('delFlg', models.CharField(choices=[('0', '有効'), ('1', '無効')], default='0', max_length=1, verbose_name='適用状態')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='登録日付')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新日付')),
            ],
            options={
                'verbose_name': 'コード',
                'verbose_name_plural': 'コード管理',
            },
        ),
    ]
