# Generated by Django 3.0.8 on 2020-07-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrdMst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crdDiv', models.CharField(choices=[], db_index=True, default='0', max_length=3, verbose_name='座標分類')),
                ('itemNm', models.CharField(max_length=60, verbose_name='項目名')),
                ('itemSort', models.IntegerField(verbose_name='項目順')),
                ('crdX', models.IntegerField(verbose_name='横座標')),
                ('crdY', models.IntegerField(verbose_name='縦座標')),
                ('defVal', models.CharField(blank=True, help_text='固定文言を設定してください.', max_length=60, null=True, verbose_name='固定文言')),
                ('cmnt1', models.TextField(blank=True, help_text='60文字まで入力してください.', max_length=60, null=True, verbose_name='備考1')),
                ('cmnt2', models.TextField(blank=True, help_text='60文字まで入力してください.', max_length=60, null=True, verbose_name='備考2')),
                ('delFlg', models.CharField(choices=[], default='0', max_length=1, verbose_name='適用状態')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='登録日付')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新日付')),
            ],
            options={
                'verbose_name': '座標',
                'verbose_name_plural': '座標管理',
            },
        ),
    ]
